name=str(input("Enter your name: "))
age=int(input("Enter your age: "))
address=str(input("Enter your address: "))
print("your name is:",name)
print("your age is:",age)
print("your address is:",address)
